export const TIMEZONES = [
  // America
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Anchorage',
  'America/Adak',
  'America/Phoenix',
  'America/Detroit',
  'America/Toronto',
  'America/Vancouver',
  'America/Edmonton',
  'America/Winnipeg',
  'America/Halifax',
  'America/St_Johns',
  'America/Mexico_City',
  'America/Guatemala',
  'America/Costa_Rica',
  'America/Panama',
  'America/Havana',
  'America/Jamaica',
  'America/Santo_Domingo',
  'America/Puerto_Rico',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/La_Paz',
  'America/Santiago',
  'America/Asuncion',
  'America/Montevideo',
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'America/Managua',

  // Europe
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Madrid',
  'Europe/Rome',
  'Europe/Vienna',
  'Europe/Zurich',
  'Europe/Prague',
  'Europe/Warsaw',
  'Europe/Stockholm',
  'Europe/Oslo',
  'Europe/Copenhagen',
  'Europe/Helsinki',
  'Europe/Athens',
  'Europe/Bucharest',
  'Europe/Sofia',
  'Europe/Dublin',
  'Europe/Lisbon',
  'Europe/Istanbul',
  'Europe/Moscow',

  // Asia
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Dhaka',
  'Asia/Karachi',
  'Asia/Kathmandu',
  'Asia/Colombo',
  'Asia/Bangkok',
  'Asia/Singapore',
  'Asia/Kuala_Lumpur',
  'Asia/Jakarta',
  'Asia/Ho_Chi_Minh',
  'Asia/Manila',
  'Asia/Hong_Kong',
  'Asia/Macau',
  'Asia/Shanghai',
  'Asia/Taipei',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Asia/Ulaanbaatar',
  'Asia/Yangon',
  'Asia/Riyadh',
  'Asia/Qatar',
  'Asia/Kuwait',
  'Asia/Baghdad',
  'Asia/Tehran',
  'Asia/Baku',
  'Asia/Tbilisi',
  'Asia/Yerevan',
  'Asia/Tashkent',
  'Asia/Almaty',

  // Australia
  'Australia/Sydney',
  'Australia/Melbourne',
  'Australia/Brisbane',
  'Australia/Perth',
  'Australia/Adelaide',
  'Australia/Darwin',
  'Australia/Hobart',

  // Africa
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Lagos',
  'Africa/Nairobi',
  'Africa/Johannesburg',
  'Africa/Addis_Ababa',
  'Africa/Accra',
  'Africa/Algiers',
  'Africa/Tunis',

  // Pacific
  'Pacific/Auckland',
  'Pacific/Fiji',
  'Pacific/Guam',
  'Pacific/Honolulu',
  'Pacific/Port_Moresby',
  'Pacific/Tahiti',

  // Atlantic
  'Atlantic/Azores',
  'Atlantic/Bermuda',
  'Atlantic/Canary',
  'Atlantic/Cape_Verde',
  'Atlantic/Reykjavik',

  // Indian
  'Indian/Maldives',
  'Indian/Mauritius',
  'Indian/Reunion',

  // UTC
  'UTC',
] as const

export type Timezone = (typeof TIMEZONES)[number]

export const TIMEZONE_OPTIONS = TIMEZONES.map((timezone) => ({
  label: timezone.replace(/_/g, ' '),
  value: timezone,
}))
